blogs/urls.py
from django.urls import path
from .views import PostListView, PostDetailView, CommentCreateView

app_name = 'blogs'

urlpatterns = [
    path('', PostListView.as_view(), name='posts'),
    path('<int:pk>/post', PostDetailView.as_view(), name='detail'),
    path('<int:pk>comment/', CommentCreateView.as_view(), name='comment'),
]

config/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static 

urlpatterns = [
    path('ckeditor/', include('ckeditor_uploader.urls')),
    path('admin/', admin.site.urls),
    path('', include('pages.urls')),
    path('', include('users.urls')),
    path('blog/', include('blogs.urls')),
    path('shop/', include('shop.urls')),
    path('order/', include('orders.urls')),

]
urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

pages/urls.py
from django.urls import path
from .views import HomePageView, ContactView

app_name = 'pages'


urlpatterns = [
    path('', HomePageView.as_view(), name='home'),
    path('contact/', ContactView.as_view(), name='contact')
]

shop/urls.py
from django.urls import path
from .views import ShopView, ProductDetailView

app_name = 'shop'


urlpatterns = [
    path('', ShopView.as_view(), name='home'),
    path('product/<int:pk>/', ProductDetailView.as_view(), name='detail')
]

blogs/models.py
from django.db import models
from django.utils.translation import gettext_lazy as _
from ckeditor_uploader.fields import RichTextUploadingField



class AutherModel(models.Model):
    full_name = models.CharField(max_length=255, verbose_name=_('full name'))
    image = models.ImageField(upload_to='auther_images/', verbose_name=_('image'))

    def __str__(self):
        return self.full_name

    class Meta:
        verbose_name = _('auther')
        verbose_name_plural = _('authers')   

class PostTagModel(models.Model):
    name = models.CharField(max_length=30, verbose_name=_('name'))  
    created_at = models.DateTimeField(auto_now_add=True, verbose_name=_('created at'))       

    def __str__(self):
        return self.name

    class Meta:
        verbose_name = _('tag')
        verbose_name_plural = _('tags')    

class PostModel(models.Model):
    title = models.CharField(max_length=255, verbose_name=_('title'))
    body = RichTextUploadingField(verbose_name=_('body'))
    main_image = models.ImageField(upload_to='main_images/', verbose_name=_('main image'))
    banner = models.ImageField(upload_to='post_banners/', verbose_name=_('banner'))
    auther = models.ForeignKey(AutherModel, related_name='posts' ,on_delete=models.RESTRICT)
    tag = models.ManyToManyField(PostTagModel, related_name='posts', verbose_name=_('tag'))
    created_at = models.DateTimeField(auto_now_add=True, verbose_name=_('created at'))

    def __str__(self):
        return f"{self.title[:100]} ..."

    class Meta:
        verbose_name = _('post')
        verbose_name_plural = _('posts')  

class CommentModel(models.Model):
    name = models.CharField(max_length=255, verbose_name=_('name'))
    email = models.EmailField(verbose_name=_('email'))
    phone = models.CharField(max_length=13, verbose_name=_('phone'))
    comment = models.TextField(verbose_name=_('comment'))
    # post = models.ForeignKey(PostModel, on_delete=models.CASCADE, related_name='comments' ,verbose_name=_('post'))
    created_at = models.DateTimeField(auto_now_add=True, verbose_name=_('created at'))


    def __str__(self):
        return f"{self.name}\n{self.email}\n{self.phone}\n{self.comment}"


    class Meta:
        verbose_name = _('comment')
        verbose_name_plural = _('comments')           

shop/models.py
from random import sample
from django.db import models
from django.utils import timezone
from django.utils.translation import gettext_lazy as _
from ckeditor_uploader.fields import RichTextUploadingField

class CategoryModel(models.Model):
    name = models.CharField(max_length=60, verbose_name=_('name'))
    created_at = models.DateTimeField(auto_now_add=True, verbose_name=_('created at'))

    def __str__(self):
        return self.name

    class Meta:
        verbose_name = 'category'
        verbose_name_plural = 'categories'


class ProductTagModel(models.Model):
    name = models.CharField(max_length=60, verbose_name=_('name'))
    created_at = models.DateTimeField(auto_now_add=True, verbose_name=_('created at'))

    def __str__(self):
        return self.name 

    class Meta:
        verbose_name = 'tag'
        verbose_name_plural = 'tags'  



class BrandModel(models.Model):
    name = models.CharField(max_length=60, verbose_name=_('name'))
    created_at = models.DateTimeField(auto_now_add=True, verbose_name=_('created at'))

    def __str__(self):
        return self.name 

    class Meta:
        verbose_name = 'brand'
        verbose_name_plural = 'brands' 


class SizeModel(models.Model):
    name = models.CharField(max_length=60, verbose_name=_('name'))
    created_at = models.DateTimeField(auto_now_add=True, verbose_name=_('created at'))

    def __str__(self):
        return self.name 

    class Meta:
        verbose_name = 'size'
        verbose_name_plural = 'sizes' 



class ColorModel(models.Model):
    code = models.CharField(max_length=60, verbose_name=_('name'))
    created_at = models.DateTimeField(auto_now_add=True, verbose_name=_('created at'))

    def __str__(self):
        return self.code

    class Meta:
        verbose_name = 'color'
        verbose_name_plural = 'colors'  

class ProductModel(models.Model):
    title = models.CharField(max_length=60, verbose_name=_('title'))
    short_description = models.CharField(max_length=255, verbose_name=_('short description'))
    long_description = RichTextUploadingField(verbose_name=_('long description'))
    price = models.FloatField(verbose_name=_('price'))
    real_price = models.FloatField(verbose_name=_('real price'), default=0)
    sale = models.BooleanField(verbose_name=_('sale'), default=False)
    discount = models.PositiveSmallIntegerField(default=0, verbose_name=_('discount'))
    main_image = models.ImageField(upload_to='products/', verbose_name=_('main image'))
    created_at = models.DateTimeField(auto_now_add=True, verbose_name=_('created at'))
    category = models.ForeignKey(
        CategoryModel, 
        on_delete=models.RESTRICT,
        related_name='products', 
        verbose_name=_('category')
    )
    tags = models.ManyToManyField(
        ProductTagModel,
        related_name='products',
        verbose_name=_('tags')
    )
    sizes = models.ManyToManyField(
    SizeModel,
    related_name='products',
    verbose_name=_('sizes')
    )
    colors = models.ManyToManyField(
    ColorModel,
    related_name='products',
    verbose_name=_('colors')
    )
    brand = models.ForeignKey(
    BrandModel,
    on_delete=models.RESTRICT,
    related_name='products',
    verbose_name=_('brand'),
    null=True
    )

    def is_discount(self):
        return bool(self.discount) 

    def new(self):
        return (timezone.now() - self.created_at).days <= 5


    def __str__(self):
        return self.title


    class Meta:
        verbose_name = 'product'
        verbose_name_plural = 'products'              

blogs/forms.py
from django import forms
from .models import CommentModel

class CommentModelForm(forms.ModelForm):


    class Meta:
        model = CommentModel
        exclude = ['created_at']

shop/forms.py
from django import forms
from .models import ColorModel

class ColorModelAdminForms(forms.ModelForm):
    code = forms.CharField(widget=forms.TextInput(attrs={'type': 'color'}))
    class Meta:
        model = ColorModel
        fields = '__all__'

blogs/views.py
from django.shortcuts import render, reverse, get_object_or_404
from django.views.generic import ListView, DetailView, CreateView
from .models import PostModel
from .forms import CommentModelForm

class PostListView(ListView):
    template_name = 'blog.html'

    def get_queryset(self):
        qs =  PostModel.objects.order_by('-id')
        tag = self.request.GET.get('tag')
        if tag:
            qs = qs.filter(tag__name=tag)
        return qs    

class PostDetailView(DetailView):
    model = PostModel
    template_name = 'blog-detail.html'


class CommentCreateView(CreateView):
    form_class = CommentModelForm


    def form_valid(self, form):
        form.instance.post = get_object_or_404(PostModel, pk=self.kwargs.get('pk'))
        return super().form_valid(form)

    def get_success_url(self):
        return reverse('blogs:detail', kwargs={'pk':self.kwargs.get('pk')})

shop/views.py
from django.db.models import Min, Max
# from unicodedata import category
from django.shortcuts import render
from django.views.generic import ListView, DetailView

from .models import ProductModel, CategoryModel, ProductTagModel, ColorModel, BrandModel, SizeModel


class ShopView(ListView):
    template_name = 'shop.html'
    paginate_by = 3

    def get_queryset(self):
        qs = ProductModel.objects.all()
        
        search = self.request.GET.get('search')
        if search:
            qs = qs.filter(title__icontains=search)

        cat = self.request.GET.get('cat')    
        if cat:
            qs = qs.filter(category_id=cat)

        tag = self.request.GET.get('tag')
        if tag:
            qs = qs.filter(tags=tag) 

        size = self.request.GET.get('size')
        if size:
            qs = qs.filter(sizes=size)

        color = self.request.GET.get('color')
        if color:
            qs = qs.filter(colors=color)

        brand = self.request.GET.get('brand')
        if brand:
            qs = qs.filter(brand_id=brand)               

        sort = self.request.GET.get('sort')
        if sort == 'price':
            qs = qs.order_by('price')
        elif sort == '-price':
            qs = qs.order_by('-price') 
        elif sort == 'sale':
            qs = qs.filter(sale=True)    

        price = self.request.GET.get('price')
        if price:
            min = price.split(';')
            max = price.split(';')
            qs = qs.filter(real_price__gte=min, real_price__lte=max)           

        
        return qs

    def get_context_data(self, *, object_list=None, **kwargs):
        data = super().get_context_data()
        data['categories'] = CategoryModel.objects.all()
        data['tags'] = ProductTagModel.objects.all()
        data['sizes'] = SizeModel.objects.all()
        data['brands'] = BrandModel.objects.all()
        data['colors'] = ColorModel.objects.all()
        data['min_price'], data['max_price'] = ProductModel.objects.aggregate(Min('real_price'), Max('real_price')).values()
        return data   


class ProductDetailView(DetailView):
    model = ProductModel
    template_name = 'shop-details.html'


    def get_context_data(self, **kwargs):
        data = super().get_context_data()
        data['products'] = ProductModel.objects.all().exclude(id=self.object.pk)[:4]
        return data

templates/blog-detail.html
{% extends 'layouts/base.html' %}

{% load static %}

{% block content %}

    <!-- Blog Details Hero Begin -->
    <section class="blog-hero spad">
        <div class="container">
            <div class="row d-flex justify-content-center">
                <div class="col-lg-9 text-center">
                    <div class="blog__hero__text">
                        <h2>{{ object.title }}</h2>
                        <ul>
                            <li>By {{ object.auther.full_name }}</li>
                            <li>{{ object.created_at|date:"F d, Y" }}</li>
                            {% if object.comments.values %}
                            <li>{{ object.comments.values.count }} Comments</li>
                            {% endif %}
                        </ul>
                    </div>
                </div>
            </div>
        </div>
    </section>
    <!-- Blog Details Hero End -->

    <!-- Blog Details Section Begin -->
    <section class="blog-details spad">
        <div class="container">
            <div class="row d-flex justify-content-center">
                <div class="col-lg-12">
                    <div class="blog__details__pic">
                        <img src="{{ object.banner.url }}" alt="{{ object.title }}">
                    </div>
                </div>
                <div class="col-lg-8">
                    <div class="blog__details__content">
                        <div class="blog__details__share">
                            <span>share</span>
                            <ul>
                                <li><a href="#"><i class="fa fa-facebook"></i></a></li>
                                <li><a href="#" class="twitter"><i class="fa fa-twitter"></i></a></li>
                                <li><a href="#" class="youtube"><i class="fa fa-youtube-play"></i></a></li>
                                <li><a href="#" class="linkedin"><i class="fa fa-linkedin"></i></a></li>
                            </ul>
                        </div>
                        <div class="blog__details__text">
                            {{ object.body|safe }}
                        </div>
                        <div class="blog__details__quote">
                            <i class="fa fa-quote-left"></i>
                            <p>“When designing an advertisement for a particular product many things should be
                                researched like where it should be displayed.”</p>
                            <h6>_ John Smith _</h6>
                        </div>
                        <div class="blog__details__option">
                            <div class="row">
                                <div class="col-lg-6 col-md-6 col-sm-6">
                                    <div class="blog__details__author">
                                        <div class="blog__details__author__pic">
                                            <img src="{{ object.auther.image.url }}" alt="{{ object.auther.full_name }}">
                                        </div>
                                        <div class="blog__details__author__text">
                                            <h5>{{ object.auther.full_name }}</h5>
                                        </div>
                                    </div>
                                </div>
                                <div class="col-lg-6 col-md-6 col-sm-6">
                                    <div class="blog__details__tags">
                                        {% for tag in object.tag.values %}
                                            <a href="{% url 'blogs:posts' %}?tag={{ tag.name }}">#{{ tag.name }}</a>
                                        {% endfor %}
                                    </div>
                                </div>
                            </div>
                        </div>
                        <div class="blog__details__btns">
                            <div class="row">
                                {% if object.get_next_by_created_at %}
                                    <div class="col-lg-6 col-md-6 col-sm-6">
                                        <a href="{% url 'blogs:detail' pk=object.get_next_by_created_at.pk %}" class="blog__details__btns__item">
                                         <p><span class="arrow_left"></span> Previous Pod</p>
                                            <h5>{{ object.get_next_by_created_at.title }}</h5>
                                        </a>
                                    </div>
                                {% endif %}
                                {% if object.get_previous_by_created_at %}
                                <div class="col-lg-6 col-md-6 col-sm-6 {% if not object.get_next_by_created_at %}offset-6{% endif %}">
                                    <a href="{% url 'blogs:detail' pk=object.get_previous_by_created_at.pk %}" class="blog__details__btns__item blog__details__btns__item--next">
                                        <p>Next Pod <span class="arrow_right"></span></p>
                                        <h5>{{ object.get_previous_by_created_at.title }}</h5>
                                    </a>
                                </div>
                                {% endif %}
                            </div>
                        </div>
                        <div class="container">
                            {% for comment in object.comments.values %}
                            <div class="row mb-3">
                                <div class="col-6"><strong>{{ comment.name }}</strong></div>
                                <div class="col-6 text-right">{{ comment.created_at|timesince }}</div>
                                <div class="col-12 mt-2">
                                    <p>
                                        {{ comment.comment }}
                                    </p>
                                </div>
                            </div>
                            {% endfor %}
                        </div>
                        <div class="blog__details__comment">
                            <h4>Leave A Comment</h4>
                            <form action="{% url 'blogs:comment' pk=object.pk %}" method="post">
                                {% csrf_token %}
                                <div class="row">
                                    <div class="col-lg-4 col-md-4">
                                        <input name="name" type="text" placeholder="Name">
                                    </div>
                                    <div class="col-lg-4 col-md-4">
                                        <input name="email" type="text" placeholder="Email">
                                    </div>
                                    <div class="col-lg-4 col-md-4">
                                        <input name="phone" type="text" placeholder="Phone">
                                    </div>
                                    <div class="col-lg-12 text-center">
                                        <textarea name="comment" placeholder="Comment"></textarea>
                                        <button type="submit" class="site-btn">Post Comment</button>
                                    </div>
                                </div>
                            </form>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </section>
    <!-- Blog Details Section End -->

{% endblock %}

templates/blog.html
{% extends 'layouts/base.html' %}
{% load static %}

{% block content %}

    <!-- Breadcrumb Section Begin -->
    <section class="breadcrumb-blog set-bg" data-setbg="{% static 'img/breadcrumb-bg.jpg' %}">
        <div class="container">
            <div class="row">
                <div class="col-lg-12">
                    {% if request.GET %}
                        <h2>#{{ request.GET.tag }}</h2>
                    {% else %}
                        <h2>Our Blog</h2>
                    {% endif %}
                </div>
            </div>
        </div>
    </section>
    <!-- Breadcrumb Section End -->

    <!-- Blog Section Begin -->
    <section class="blog spad">
        <div class="container">
            <div class="row">
                {% for post in object_list %}
                <div class="col-lg-4 col-md-6 col-sm-6">
                    <div class="blog__item">
                        <div class="blog__item__pic set-bg" data-setbg="{{ post.main_image.url }}"></div>
                        <div class="blog__item__text">
                            <span><img src="{% static 'img/icon/calendar.png' %}" alt="">{{ post.created_at|date:"d F Y" }}</span>
                            <h5>{{ post.title|title|truncatewords:"10" }}</h5>
                            <a href="{% url 'blogs:detail' post.pk %}">Read More</a>
                        </div>
                    </div>
                </div>
                {% endfor %}
            </div>
        </div>
    </section>
    <!-- Blog Section End -->

{% endblock %}    

templates/product_item.html
{% load static %}
<div class="product__item sale">
    <div class="product__item__pic set-bg" data-setbg="{{ product.main_image.url }}">
        {% if product.is_discount %}
            <span class="label">Sale</span>
        {% endif %}
        {% if product.is_new %}
            <span class="label new {% if product.is_discount %}new-mt{% endif %}">New</span>
        {% endif %}
        <ul class="product__hover">
            <li><a href="#"><img src="{% static 'img/icon/heart.png' %}" alt=""></a></li>
            <li><a href="{% url 'shop:detail' pk=product.pk %}"><img src="{% static 'img/icon/search.png' %}" alt=""></a></li>
        </ul>
    </div>
    <div class="product__item__text">
        <h6>{{ product.title }}</h6>
        <a href="#" class="add-cart">+ Add To Cart</a>
        <div class="rating">
            <i class="fa fa-star"></i>
            <i class="fa fa-star"></i>
            <i class="fa fa-star"></i>
            <i class="fa fa-star"></i>
            <i class="fa fa-star-o"></i>
        </div>
        <h5>${{ product.real_price }} {% if product.is_discount %} <del class="text-secondary">{{ product.price }}</del> {% endif %}</h5>
        <div class="product__color__select">
            {% for color in product.colors.all %}
                <label style="background-color: {{ color.code }}" for="{{ color.code }}">
                    <input type="radio" id="{{ color.code }}">
                </label>
            {% endfor %}
        </div>
    </div>
</div>

templates/shop-details.html
{% extends 'layouts/base.html' %}
{% load static %}

{% block content %}
    <!-- Shop Details Section Begin -->
    <section class="shop-details">
        <div class="product__details__pic">
            <div class="container">
                <div class="row">
                    <div class="col-lg-12">
                        <div class="product__details__breadcrumb">
                            <a href="{% url 'pages:home' %}">Home</a>
                            <a href="{% url 'shop:home' %}">Shop</a>
                            <span>Product Details</span>
                        </div>
                    </div>
                </div>
                <div class="row">
                    <div class="col-lg-3 col-md-3">
                        <ul class="nav nav-tabs" role="tablist">
                            <li class="nav-item">
                                <a class="nav-link active" data-toggle="tab" href="#tabs-1" role="tab">
                                    <div class="product__thumb__pic set-bg" data-setbg="{% static 'img/shop-details/thumb-1.png' %}">
                                    </div>
                                </a>
                            </li>
                            <li class="nav-item">
                                <a class="nav-link" data-toggle="tab" href="#tabs-2" role="tab">
                                    <div class="product__thumb__pic set-bg" data-setbg="{% static 'img/shop-details/thumb-2.png' %}">
                                    </div>
                                </a>
                            </li>
                            <li class="nav-item">
                                <a class="nav-link" data-toggle="tab" href="#tabs-3" role="tab">
                                    <div class="product__thumb__pic set-bg" data-setbg="{% static 'img/shop-details/thumb-3.png' %}">
                                    </div>
                                </a>
                            </li>
                            <li class="nav-item">
                                <a class="nav-link" data-toggle="tab" href="#tabs-4" role="tab">
                                    <div class="product__thumb__pic set-bg" data-setbg="{% static 'img/shop-details/thumb-4.png' %}">
                                        <i class="fa fa-play"></i>
                                    </div>
                                </a>
                            </li>
                        </ul>
                    </div>
                    <div class="col-lg-6 col-md-9">
                        <div class="tab-content">
                            <div class="tab-pane active" id="tabs-1" role="tabpanel">
                                <div class="product__details__pic__item">
                                    <img src="{% static 'img/shop-details/product-big-2.png' %}" alt="">
                                </div>
                            </div>
                            <div class="tab-pane" id="tabs-2" role="tabpanel">
                                <div class="product__details__pic__item">
                                    <img src="{% static 'img/shop-details/product-big-3.png' %}" alt="">
                                </div>
                            </div>
                            <div class="tab-pane" id="tabs-3" role="tabpanel">
                                <div class="product__details__pic__item">
                                    <img src="{% static 'img/shop-details/product-big.png' %}" alt="">
                                </div>
                            </div>
                            <div class="tab-pane" id="tabs-4" role="tabpanel">
                                <div class="product__details__pic__item">
                                    <img src="{% static 'img/shop-details/product-big-4.png' %}" alt="">
                                    <a href="https://www.youtube.com/watch?v=8PJ3_p7VqHw&list=RD8PJ3_p7VqHw&start_radio=1" class="video-popup"><i class="fa fa-play"></i></a>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
        <div class="product__details__content">
            <div class="container">
                <div class="row d-flex justify-content-center">
                    <div class="col-lg-8">
                        <div class="product__details__text">
                            <h4>{{ object.title }}</h4>
                            <div class="rating">
                                <i class="fa fa-star"></i>
                                <i class="fa fa-star"></i>
                                <i class="fa fa-star"></i>
                                <i class="fa fa-star"></i>
                                <i class="fa fa-star-o"></i>
                                <span> - 5 Reviews</span>
                            </div>
                            <h3>${{ object.real_price }} {% if object.is_discount %}<span>{{ object.price }}</span>{% endif %}</h3>
                            <p>
                                {{ object.short_description }}
                            </p>
                            <div class="product__details__option">
                                <div class="product__details__option__size">
                                    <span>Size:</span>
                                    {% for size in object.sizes.all %}
                                        <label for="{{ size.name }}">{{ size.name }}
                                            <input type="radio" id="{{ size.name }}">
                                        </label>
                                    {% endfor %}
                                </div>
                                <div class="product__details__option__color">
                                    <span>Color:</span>
                                    {% for color in object.colors.all %}
                                        <label style="background-color: {{ color.code }}" for="{{ color.code }}">
                                            <input type="radio" id="{{ color.code }}">
                                        </label>
                                    {% endfor %}
                                </div>
                            </div>
                            <div class="product__details__cart__option">
                                <div class="quantity">
                                    <div class="pro-qty">
                                        <input type="text" value="1">
                                    </div>
                                </div>
                                <a href="#" class="primary-btn">add to cart</a>
                            </div>
                            <div class="product__details__btns__option">
                                <a href="#"><i class="fa fa-heart"></i> add to wishlist</a>
                                <a href="#"><i class="fa fa-exchange"></i> Add To Compare</a>
                            </div>
                            <div class="product__details__last__option">
                                <h5><span>Guaranteed Safe Checkout</span></h5>
                                <img src="{% static 'img/shop-details/details-payment.png' %}" alt="">
                                <ul>
                                    <li><span>Category:</span>{{ object.category.name }}</li>
                                    <li><span>Tags:</span>
                                        {% for tag in object.tags.all %}
                                            #{{ tag.name }}
                                        {% endfor %}
                                    </li>
                                </ul>
                            </div>
                        </div>
                    </div>
                </div>
                <div class="row">
                    <div class="col-lg-12">
                        <div class="product__details__tab">
                            <ul class="nav nav-tabs" role="tablist">
                                <li class="nav-item">
                                    <a class="nav-link active" data-toggle="tab" href="#tabs-5"
                                    role="tab">Description</a>
                                </li>
                            </ul>
                            <div class="tab-content">
                                <div class="tab-pane active" id="tabs-5" role="tabpanel">
                                    <div class="product__details__tab__content">
                                        {{ object.long_description|safe }}
                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </section>
    <!-- Shop Details Section End -->

    <!-- Related Section Begin -->
    <section class="related spad">
        <div class="container">
            <div class="row">
                <div class="col-lg-12">
                    <h3 class="related-title">Related Product</h3>
                </div>
            </div>
            <div class="row">
                {% for product in products %}
                <div class="col-lg-3 col-md-6 col-sm-6 col-sm-6">
            
                    {% include 'product_item.html' %}
                
                </div>
                {% endfor %}
                </div>
            </div>
    </section>
    <!-- Related Section End -->

{% endblock %}